name: rapid-photo-downloader
version: '0.9.0b5'
summary: Download, rename and back up photos and videos from cameras and other devices
description: |
  Rapid Photo Downloader imports photos and videos from cameras, phones,
  memory cards and other devices at high speed. It can be configured to
  rename photos and videos with meaningful filenames you specify. It can also
  back up photos and videos as they are downloaded. It downloads from and backs
  up to multiple devices simultaneously.

grade: devel
confinement: classic

apps:
  rapid-photo-downloader:
    command: rapid-photo-downloader
    plugs: [home, network, network-bind, unity7, x11, mount-observe]

parts:
  rapid-photo-downloader:
    plugin: python
    source: ../
    python-packages:
     - PyQt5
    stage-packages:
     - libgphoto2-6
     - libimage-exiftool-perl
     - exiv2
     - libmediainfo0v5
     - libraw-bin
     - python3-gi
     - gir1.2-gexiv2-0.10
     - gir1.2-gudev-1.0
     - gir1.2-udisks-2.0
     - gir1.2-notify-0.7
     - gir1.2-glib-2.0
     - gir1.2-gstreamer-1.0
    build-packages:
     - build-essential
     - libgphoto2-dev
     - python3-dev
     - libzmq3-dev
