name: rapid-photo-downloader
base: core18 # the base snap is the execution environment for this snap
version: '0.9.20' # just for humans, typically '1.2+git' or '1.3.2'
summary: Download, rename and back up photos and videos from cameras and other devices
description: |
  Rapid Photo Downloader imports photos and videos from cameras, phones,
  memory cards and other devices at high speed. Configure it to rename photos
  and videos with meaningful filenames you specify. It can also back up photos
  and videos as they are downloaded. It downloads from and backs up to multiple
  devices simultaneously.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  rapid-photo-downloader:
    command: rapid-photo-downloader
    extensions: [gnome-3-28]
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.22/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.22.1/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.22/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.22.1/"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$LD_LIBRARY_PATH"
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - home
      - network
      - network-bind
      - network-control
      - camera
      - raw-usb
      - x11
      - unity7
      - wayland
      - desktop
      - opengl
      - udisks2
      - removable-media

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgphoto2:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgphoto2
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgphoto2_port:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgphoto2_port

parts:
  rapid-photo-downloader:
    plugin: python
    source: .
    python-packages:
      - pyheif
      - arrow
    stage-packages:
      - libgphoto2-6
      - libimage-exiftool-perl
      - perl
      - exiv2
      - libmediainfo0v5
      - libraw16
      - libnotify-bin
      - python3-gi
      - gir1.2-gexiv2-0.10
      - gir1.2-gudev-1.0
      - gir1.2-udisks-2.0
      - gir1.2-notify-0.7
      - gir1.2-glib-2.0
      - gir1.2-gstreamer-1.0
      - libzmq5
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-good
      - libheif1
      - libde265-0
      - libx265-146
      - python3-pyqt5
      - qt5-image-formats-plugins
      - python3-distutils
      - python3-pil
      - python3-gphoto2
      - python3-setuptools
      - python3-psutil
      - python3-zmq
      - python3-tornado
      - python3-xdg
      - python3-dateutil
      - python3-rawkit
      - python3-pyprind
      - python3-colorlog
      - python3-easygui
      - python3-colour
      - python3-pymediainfo
      - python3-sortedcontainers
      - python3-requests
      - python3-tenacity
      - libgpm2
      - libslang2
      - freeglut3
      - libglu1-mesa
      - libgl1-mesa-glx
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    build-packages:
      - build-essential
      - intltool
      - libheif-dev
      - libde265-dev
      - libx265-dev
      - libraw-dev



